FROM node:20-alpine

WORKDIR /app

ENV PROJECT_ROOT=/monorepo/

COPY package.json yarn.lock ${PROJECT_ROOT}
COPY packages/server/package.json ${PROJECT_ROOT}/packages/server/

RUN yarn install --frozen-lockfile

COPY . ${PROJECT_ROOT}

WORKDIR ${PROJECT_ROOT}/packages/server

EXPOSE 3333

CMD ["yarn", "dev"]
